/**
 * Panel 2 — Layout Counterfactuals.
 *
 * Lists every candidate strategy from DecisionTrace.candidateScores with its
 * overall score, sorted descending. The winner carries a "chosen" badge.
 * Clicking a non-winning row shows a plain-language explanation of why it lost,
 * generated by explainLoss() from the actual ScoreBreakdown numbers.
 *
 * Selection state is keyed by strategy name and reset (via `key` on this
 * component in App.tsx) every time the surface changes.
 */

import { useState } from "react";
import type { DecisionTrace } from "../core/trace";
import { explainLoss } from "../core/trace";
import type { ScoreBreakdown } from "../core/scoring";

function tier(score: number): "high" | "mid" | "low" {
  if (score >= 80) return "high";
  if (score >= 50) return "mid";
  return "low";
}

export function LayoutCounterfactuals({
  trace,
}: {
  trace: DecisionTrace;
}): JSX.Element {
  const [selected, setSelected] = useState<string | null>(null);

  const ranked = [...trace.candidateScores].sort(
    (a, b) => b.score.overall - a.score.overall,
  );
  const winning = trace.candidateScores.find(
    (c) => c.strategy === trace.winningStrategy,
  );

  return (
    <section className="ale-panel" data-testid="layout-counterfactuals">
      <h2 className="ale-h2">Layout Counterfactuals</h2>
      <p className="ale-note">
        Every strategy tried, best score first. Click a losing one to see why.
      </p>

      <ul className="ale-list">
        {ranked.map(({ strategy, score }) => {
          const isWinner = strategy === trace.winningStrategy;
          const isSelected = strategy === selected;
          return (
            <li key={strategy}>
              <button
                type="button"
                className="ale-cand"
                data-testid="candidate-row"
                data-strategy={strategy}
                data-winner={isWinner ? "true" : "false"}
                onClick={() =>
                  isWinner
                    ? undefined
                    : setSelected(isSelected ? null : strategy)
                }
              >
                <span className="ale-cand-head">
                  <span>
                    {strategy}
                    {isWinner && (
                      <span
                        className="ale-badge"
                        data-testid="chosen-badge"
                        style={{ marginLeft: 8 }}
                      >
                        CHOSEN
                      </span>
                    )}
                  </span>
                  <span className="ale-cand-score">{score.overall}/100</span>
                </span>
                <span className="ale-cand-bar" data-tier={tier(score.overall)}>
                  <i style={{ transform: `scaleX(${score.overall / 100})` }} />
                </span>
              </button>

              {isSelected && !isWinner && winning && (
                <p className="ale-loss" data-testid="loss-explanation">
                  {explainLoss(score, winning.score as ScoreBreakdown)}
                </p>
              )}
            </li>
          );
        })}
      </ul>
    </section>
  );
}
