/**
 * Panel 2 — Layout Counterfactuals.
 *
 * Lists every candidate strategy from DecisionTrace.candidateScores with its
 * overall score, sorted descending. The winner carries a "chosen" badge.
 * Clicking a non-winning row shows a plain-language explanation of why it lost,
 * generated by explainLoss() from the actual ScoreBreakdown numbers.
 *
 * Selection state is keyed by strategy name and reset (via `key` on this
 * component in App.tsx) every time the surface changes, so no stale "why it
 * lost" text lingers from a previous surface.
 */

import { useState } from "react";
import type { DecisionTrace } from "../core/trace";
import { explainLoss } from "../core/trace";
import type { ScoreBreakdown } from "../core/scoring";

export function LayoutCounterfactuals({
  trace,
}: {
  trace: DecisionTrace;
}): JSX.Element {
  const [selected, setSelected] = useState<string | null>(null);

  const ranked = [...trace.candidateScores].sort(
    (a, b) => b.score.overall - a.score.overall,
  );
  const winning = trace.candidateScores.find(
    (c) => c.strategy === trace.winningStrategy,
  );

  return (
    <section data-testid="layout-counterfactuals" style={{ minWidth: 280 }}>
      <h2 style={{ fontSize: 14, margin: "0 0 6px" }}>Layout Counterfactuals</h2>
      <p style={{ fontSize: 11, color: "#666", margin: "0 0 8px" }}>
        Every strategy tried, best score first. Click a losing one to see why.
      </p>

      <ul style={{ listStyle: "none", padding: 0, margin: 0 }}>
        {ranked.map(({ strategy, score }) => {
          const isWinner = strategy === trace.winningStrategy;
          const isSelected = strategy === selected;
          return (
            <li key={strategy} style={{ marginBottom: 4 }}>
              <button
                type="button"
                data-testid="candidate-row"
                data-strategy={strategy}
                data-winner={isWinner ? "true" : "false"}
                onClick={() =>
                  isWinner
                    ? undefined
                    : setSelected(isSelected ? null : strategy)
                }
                style={{
                  width: "100%",
                  textAlign: "left",
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  gap: 8,
                  fontSize: 12,
                  padding: "6px 8px",
                  border: isSelected ? "1px solid #0066cc" : "1px solid #ddd",
                  background: isWinner ? "#eef7ee" : "#fff",
                  cursor: isWinner ? "default" : "pointer",
                }}
              >
                <span>
                  {strategy}
                  {isWinner && (
                    <span
                      data-testid="chosen-badge"
                      style={{
                        marginLeft: 8,
                        fontSize: 10,
                        fontWeight: 700,
                        color: "#2a7",
                        border: "1px solid #2a7",
                        borderRadius: 3,
                        padding: "1px 4px",
                      }}
                    >
                      CHOSEN
                    </span>
                  )}
                </span>
                <b>{score.overall}/100</b>
              </button>

              {isSelected && !isWinner && winning && (
                <p
                  data-testid="loss-explanation"
                  style={{
                    fontSize: 12,
                    lineHeight: 1.4,
                    margin: "4px 0 8px",
                    padding: "6px 8px",
                    background: "#fff8e1",
                    border: "1px solid #f0e0a0",
                  }}
                >
                  {explainLoss(
                    score,
                    winning.score as ScoreBreakdown,
                  )}
                </p>
              )}
            </li>
          );
        })}
      </ul>
    </section>
  );
}
